import type { Metadata } from "next";
import {  Noto_Sans_JP, Outfit,  } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const notoSans = Noto_Sans_JP({
  variable: "--font-noto",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} ${outfit.variable} antialiased`}
      >
        <div className="sticky top-0 left-0 z-999 bg-[#ffffff75]">
          <Navbar/>
        </div>
        <div className="">
          {children}
        </div>
      </body>
    </html>
  );
}
